# Generated by Django 4.2.7 on 2025-10-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='busregistration',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='busregistration',
            name='travel_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='BusLocation',
        ),
    ]
